### PR TITLE
PostFix Added

### PR DESCRIPTION
**Pull request by bezyaev**
Hello. Created postFix param for changing prefix destination at the end. Tests included

### CODE REVIEW

**Comment by duterte** [comment]
Cool, thumbs up

**Comment by nosir** [comment]
Thanks, I changed the option name to `tailPrefix`, otherwise, postfix sounds like something fully opposite to prefix

**Comment by duterte** [comment]
I'm now happy ...

**Comment by Torfab** [comment]
Hello, The delete is very buggy with tailPrefix, you have to manually move the cursor around. 
Did you think about any workaround to avoid this?

**Pull request merged**
