### PR TITLE
Fix for signBeforePrefix breaking getRawValue

### PR DESCRIPTION
**Pull request by rob-raymond-sdc**
Should hopefully fix issue #524 in a non-breaking manner.

### CODE REVIEW

**Comment by rob-raymond-sdc** [comment]
Has a small issue that needs fixing

**Comment by rob-raymond-sdc** [comment]
Updated unit test parameters and added unit test for getPrefixStrippedValue with signBeforePrefix

**Comment by nosir** [comment]
Thanks, even though when this kinda format could be used? `-test123.45`

**Comment by rob-raymond-sdc** [comment]
> Thanks, even though when this kinda format could be used? `-test123.45`

We use it to display monetary values, which are sometimes negative (ie. for discounts, refunds, etc.) - eg. "-£123.45". Sometimes you might also want to display currency codes, ie. "-USD123.45".

**Pull request merged**
