### PR TITLE
Including suffix option to cleave

### PR DESCRIPTION
**Pull request by shortdiv**
Add the option to include suffix to cleave. This will allow for cases with % for example to be handled appropriately.

### CODE REVIEW

**Comment by bernatfortet** [comment]
Could this branch be merged?

**Comment by oefimov** [comment]
Really required for locales with suffix-styled currency symbols.

Any chance of merge and release? Any help needed?

**Comment by matmasoni** [comment]
+1

**Comment by nosir** [comment]
As @matmasoni noted, this pr still needs lots work, particularly it has the following issue:
- Deleting not behaves correctly
- It does't contain logic in adding suffix for custom input type (which is major)
- The init state doesn't have suffix string showing in the input field

It's been a while so I'm closing this off.

We might add some suffix option only for numeral and will update here.

Cheers.

**Comment by voodoo6** [comment]
+1 here for suffix option, needed for units (eg. 200m²)

**Comment by alxndr-w** [comment]
@voodoo6 have a look at this "works-for-me" solution

https://github.com/nosir/cleave.js/issues/189#issuecomment-725326591

**Comment by Rsawadogo** [comment]
Hi,

Thanks for this interesting topic. I am interested in this discussion.
can I use parameter (suffix = '%') for numbers or this parameter is not supported by js.cleave yet?
thank you for your help

**Comment by Rsawadogo** [comment]
Hi,

Thanks for this interesting topic. I am interested in this discussion.
can I use parameter (suffix = '%') for numbers or this parameter is not supported by cleave.js yet?

thank you for your help

**Pull request closed without merging**
