### PR TITLE
Remove componentWillReceiveProps usage for concurrent mode

### LINKED ISSUE #510: React 16.x deprecation warning about componentWillReceiveProps
When using Cleave.js with a React 16.x app (1.6.9 in my case), you get the following deprecation warning in the console:

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Component
```

### PR DESCRIPTION
**Pull request by whatknight**
Fixes #510. This lifecycle method is unsafe for concurrent mode.

Key change here is moving all the logic from cWRP to componentDidUpdate. I still need to test it out, but wanted to start the conversation. 

Is there any reason this is using react-create-class instead of a regular class?

### CODE REVIEW

**Comment by whatknight** [comment]
Tested this out successfully.

**Comment by giamir** [comment]
Nice @whatknight! Any chance this could be double checked and merged in @nosir?
Thanks a lot.

**Comment by brandontle** [comment]
Hey @nosir any reservations with merging this in? Would love to see this error cleared up. Thanks @whatknight!

**Comment by cht8687** [comment]
@whatknight thanks for the fix. 

@brandontle  merged this and will release a new version soon.

**Pull request merged**
