### PR TITLE
Emit custom event when value gets changed

### PR DESCRIPTION
**Pull request by ankurk91**
Hi, there

I know that you guys have no plans to support other java-script frameworks but adding this piece of code into this library will really help developers to support those framework.

### What was the issue
* When `cleave.js` changes the input value; there is no way to detect if the value has been changed.
* The workaround was to listen to `input` event but it only gets triggered when user types in

### How this PR solve this issue
* `cleave.js` now emits an event by which outside java-script can listen and perform the actions like updating the scope or v-model.

### Example in vue.js
```html
<input type="tel" @update-value="doSomethingWhenValueChanged"/>
```
### Example in pure js
```html
<input type="tel" id="input-phone">
<script>
var input = document.querySelector('#input-phone');
  var cleave = new Cleave(input);
  input.addEventListener('update-value', function (e) {
    // update v-model here
    var vmodel = cleave.getRawValue();
  })
</script>
```
Feel free to change the event name, right now it named as `update-value`.
FYI: The name should NOT be one of native events, like `input` or `change`

`dispatchEvent` already has wide browser support 
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent

Thanks.

### CODE REVIEW

**Comment by nosir** [comment]
For pure js, you can just do this:
```
var cleave = new Cleave('.test-input', {
    creditCard: true
});
input.addEventListener('input', function () {
    console.log(cleave.getRawValue());
});

```

For vue, I think you can also put the logic in `@input`

**Comment by ankurk91** [comment]
Yes, `@input` event can handle most of the cases but not all for example `cut` event (CTRL+X).

Cleave.js itself [relies](https://github.com/nosir/cleave.js/blob/2a1225f7c7684c99b1b2ca07f6aa7c8c1b01a2c7/src/Cleave.js#L51-L55) on native `input` and `cut` events.

That means outside javascript can never know when `cleave.js` has finished its internal calculations, because both are listening to same event and my callback may gets executed before yours.

Emitting a separate event right after cleave.js finished its calculations will ensure that there is no task pending from library and we can perform our tasks (update v-model) now.

**Comment by nosir** [comment]
Ah, okay. I see your point now.
However, I don't think we should dispatch the custom event to send cleave change events here.
To make it more clear and controllable, I will add a new option `onValueChange`, you can just pass it in like:
```
new Vue({
    el: '#app',
    data: {
        card: null,
        options: {
            creditCard: true,
            onValueChanged: function(e) {
                console.log(e.target); // {value: '5100-1111', rawValue: '51001111'}
            }
        }
    }
});
```
And this will be triggered when cleave data updating happens. Also this will be consistent as how it works in React component.
I will let you know when it's release so you can pull and update your app.

**Comment by ankurk91** [comment]
Thanks, this will work. Will be waiting for this feature to be released.

**Comment by nosir** [comment]
@ankurk91 just released in 1.3.1, tested your code, cut works now

**Pull request closed without merging**
