### PR TITLE
Cursor position should be restored after change

### PR DESCRIPTION
**Pull request by reborg**
I think this solves the jump of the cursor to the right for every change mentioned here https://github.com/nosir/cleave.js/issues/25, at least in some of the use cases I've tested on the number formatter. I didn't try this on the react part (although I think the change applies the same) or other type of inputs.

### CODE REVIEW

**Comment by reborg** [comment]
Last commit "Added new custom option to prevent stripLeadingZeroes" is not related, but added option default doesn't change current behaviour, only if you explicitly set it to false. The reason for not stripping zeroes is because if you have a number like "100,000" and you want to change it to "200,000" you don't necessary want to see it going to "0" before typing all the zeroes again. This option preserves the leading zeroes in this case.

**Comment by Viincenttt** [comment]
Very nice, you are my hero!

**Comment by mrlundis** [comment]
@reborg Awesome! Seems like this breaks the react component tho :/

**Comment by mdziekon** [comment]
@reborg as you can see, I've fixed the problem with React component being broken and created a separate PR (since I don't know what should be the proper way of me pushing changes to your branch here). If there is something wrong with that, please contact me so we can resolve it whatever way you like (as you are the original author of the fix).

**Comment by felixhorro** [comment]
Any update on this?
Very useful PR, I need this!

Thanks.

**Comment by jperelli** [comment]
> since I don't know what should be the proper way of me pushing changes to your branch here

@mdziekon you can do a pull request here https://github.com/reborg/cleave.js if you want to do that

**Comment by grk** [comment]
There's an edge case here, with the following options: `{ numeral: true, prefix: "£" }` the cursor jumps to the wrong place when adding characters that change the number of decimal separators.

**Comment by nosir** [comment]
Thanks and sorry for the delay @reborg Awesome work!
So I finally got chance to test it and fix a couple of minor things.
React component is broken so I commented it out for now, will have a look at @mdziekon 's PR soon.

**Pull request merged**
