### PR TITLE
Prohibit month/day being 0 in DateFormatter (#31)

### PR DESCRIPTION
**Pull request by heejongahn**
As pointed out via issue #31, the month or day should not be allowed
  to be zero. This commit only handles that issue, and does not add
  monthly-based date formatting.

### CODE REVIEW

**Comment by trjiang** [comment]
Hey @heejongahn thanks for the PR and test cases 👍 , sorry we did a hotfix yesterday night, so could you please solve your conflicts? Basically, just exclude any file in `dist` folder, we will regenerate js.

**Comment by heejongahn** [comment]
Sure, no problem. I'll solve it as soon as I get home this evening.
2016. 7. 15. 06:38에 "Jeff J" <notifications@github.com>님이 작성:

**Comment by heejongahn** [comment]
As you said :) 👍

**Comment by nosir** [comment]
@trjiang This change breaks the backspace delete character behaviour, please follow general test process before merging, thanks.

No worries. I added a hotfix commit, will fix from my side.

**Comment by heejongahn** [comment]
Aha, I should've considered that.. Thank you for a hotfix @nosir !

**Comment by nosir** [comment]
@heejongahn no problem

**Pull request merged**
